definitions:
  caches:
    pnpm: $BITBUCKET_CLONE_DIR/.pnpm-store

pipelines:
  branches:
    staging:
      - step:
          name: Build and test
          image: node:18.12.1
          script:
            - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
            - pnpm install
            - pnpm run build
            - pnpx wrangler pages publish .svelte-kit/cloudflare --project-name=fs-site-2022-staging --branch staging
          caches:
            - pnpm
    production:
      - step:
          name: Build and test
          image: node:18.12.1
          script:
            - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
            - pnpm install
            - pnpm run build
            - pnpx svelte-sitemap --domain https://futureshirts.co --out-dir=.svelte-kit/cloudflare
            - pnpx wrangler pages publish .svelte-kit/cloudflare --project-name=fs-site-2022 --branch production
          caches:
            - pnpm
